version: '3'

services:
  postgres:
    image: postgres:13
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: always
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: {}
